export const PUBLIC_SITE_URL = 'https://ioi.foundation';
export const PUBLIC_SITE_NAME = 'IOI Foundation';
export const PUBLIC_DEFAULT_LOCALE = 'en-US';

export const PUBLIC_LOCALES = {
  'en-US': {
    segment: '',
    htmlLang: 'en-US',
    hrefLang: 'en-US',
    ogLocale: 'en_US',
    label: 'English',
  },
  'es-ES': {
    segment: 'es',
    htmlLang: 'es-ES',
    hrefLang: 'es-ES',
    ogLocale: 'es_ES',
    label: 'Español',
  },
  'fr-FR': {
    segment: 'fr',
    htmlLang: 'fr-FR',
    hrefLang: 'fr-FR',
    ogLocale: 'fr_FR',
    label: 'Français',
  },
  'de-DE': {
    segment: 'de',
    htmlLang: 'de-DE',
    hrefLang: 'de-DE',
    ogLocale: 'de_DE',
    label: 'Deutsch',
  },
};

export const PUBLIC_ROUTE_ORDER = ['home', 'charter', 'bylaws', 'governance', 'research'];

export const PUBLIC_ROUTES = {
  home: {
    path: '/',
    priority: '1.0',
    changefreq: 'weekly',
    ogType: 'website',
    schemaType: 'WebPage',
    name: {
      'en-US': 'IOI Foundation',
      'es-ES': 'Fundación IOI',
      'fr-FR': 'Fondation IOI',
      'de-DE': 'IOI Stiftung',
    },
    title: {
      'en-US': 'IOI Foundation | Protocol Stewardship, Governance, and Research',
      'es-ES': 'Fundación IOI | Custodia del protocolo, gobernanza e investigación',
      'fr-FR': 'Fondation IOI | Gouvernance, recherche et stewardship du protocole',
      'de-DE': 'IOI Stiftung | Protokoll-Stewardship, Governance und Forschung',
    },
    description: {
      'en-US': 'A public institution for protocol neutrality, governance, long-horizon technical research, and enforceable constitutional limits on autonomous systems.',
      'es-ES': 'Una institución pública para la neutralidad del protocolo, la gobernanza, la investigación técnica de largo plazo y límites constitucionales exigibles sobre sistemas autónomos.',
      'fr-FR': 'Une institution publique dédiée à la neutralité du protocole, à la gouvernance, à la recherche technique de long terme et à des limites constitutionnelles opposables aux systèmes autonomes.',
      'de-DE': 'Eine öffentliche Institution für Protokollneutralität, Governance, langfristige technische Forschung und durchsetzbare verfassungsrechtliche Grenzen für autonome Systeme.',
    },
    socialTitle: {
      'en-US': 'IOI Foundation',
      'es-ES': 'Fundación IOI',
      'fr-FR': 'Fondation IOI',
      'de-DE': 'IOI Stiftung',
    },
    socialDescription: {
      'en-US': 'Governance, research, and protocol integrity for the long term.',
      'es-ES': 'Gobernanza, investigación e integridad del protocolo a largo plazo.',
      'fr-FR': 'Gouvernance, recherche et intégrité du protocole sur le long terme.',
      'de-DE': 'Governance, Forschung und Protokollintegrität für den langen Zeithorizont.',
    },
    noscriptHeading: {
      'en-US': 'IOI Foundation',
      'es-ES': 'Fundación IOI',
      'fr-FR': 'Fondation IOI',
      'de-DE': 'IOI Stiftung',
    },
    noscriptBody: {
      'en-US': 'This public site publishes the Foundation Charter, corporate bylaws, governance framework, and technical research agenda.',
      'es-ES': 'Este sitio público publica la Carta de la Fundación, los estatutos corporativos, el marco de gobernanza y la agenda de investigación técnica.',
      'fr-FR': 'Ce site public publie la Charte de la Fondation, les statuts sociaux, le cadre de gouvernance et le programme de recherche technique.',
      'de-DE': 'Diese öffentliche Website veröffentlicht die Stiftungs-Charta, die Gesellschaftsstatuten, das Governance-Rahmenwerk und die technische Forschungsagenda.',
    },
  },
  charter: {
    path: '/charter',
    priority: '0.9',
    changefreq: 'monthly',
    ogType: 'article',
    schemaType: 'TechArticle',
    name: {
      'en-US': 'Foundation Charter',
      'es-ES': 'Carta de la Fundación',
      'fr-FR': 'Charte de la Fondation',
      'de-DE': 'Stiftungs-Charta',
    },
    title: {
      'en-US': 'The IOI Foundation Charter and Immutable Constitution',
      'es-ES': 'La Carta de la Fundación IOI y Constitución Inmutable',
      'fr-FR': 'La Charte de la Fondation IOI et Constitution immuable',
      'de-DE': 'Die IOI Stiftungs-Charta und unveränderliche Verfassung',
    },
    description: {
      'en-US': 'The constitutional document defining enforceable limits on protocol action, mutation, and governance under bounded human-rooted authority.',
      'es-ES': 'El documento constitucional que define límites exigibles sobre la acción, mutación y gobernanza del protocolo bajo una autoridad humana acotada.',
      'fr-FR': 'Le document constitutionnel qui définit des limites opposables à l’action, à la mutation et à la gouvernance du protocole sous une autorité humaine bornée.',
      'de-DE': 'Das Verfassungsdokument, das durchsetzbare Grenzen für Protokollhandeln, Mutation und Governance unter begrenzter menschlicher Root-Autorität definiert.',
    },
    socialTitle: {
      'en-US': 'Foundation Charter',
      'es-ES': 'Carta de la Fundación',
      'fr-FR': 'Charte de la Fondation',
      'de-DE': 'Stiftungs-Charta',
    },
    socialDescription: {
      'en-US': 'An immutable constitutional envelope for protocol action and governance.',
      'es-ES': 'Un marco constitucional inmutable para la acción y la gobernanza del protocolo.',
      'fr-FR': 'Une enveloppe constitutionnelle immuable pour l’action et la gouvernance du protocole.',
      'de-DE': 'Ein unveränderlicher verfassungsrechtlicher Rahmen für Protokollhandeln und Governance.',
    },
    noscriptHeading: {
      'en-US': 'Foundation Charter',
      'es-ES': 'Carta de la Fundación',
      'fr-FR': 'Charte de la Fondation',
      'de-DE': 'Stiftungs-Charta',
    },
    noscriptBody: {
      'en-US': 'Read the constitutional framework defining bounded authority, verifiable action, and sovereign human custody within the IOI protocol.',
      'es-ES': 'Lee el marco constitucional que define autoridad acotada, acción verificable y custodia humana soberana dentro del protocolo IOI.',
      'fr-FR': 'Consulte le cadre constitutionnel qui définit l’autorité bornée, l’action vérifiable et la garde humaine souveraine au sein du protocole IOI.',
      'de-DE': 'Lesen Sie den verfassungsrechtlichen Rahmen, der begrenzte Autorität, verifizierbares Handeln und souveräne menschliche Verwahrung im IOI-Protokoll definiert.',
    },
  },
  bylaws: {
    path: '/bylaws',
    priority: '0.8',
    changefreq: 'monthly',
    ogType: 'article',
    schemaType: 'DigitalDocument',
    name: {
      'en-US': 'IOI Labs, Inc. Bylaws',
      'es-ES': 'Estatutos de IOI Labs, Inc.',
      'fr-FR': 'Statuts de IOI Labs, Inc.',
      'de-DE': 'Satzung von IOI Labs, Inc.',
    },
    title: {
      'en-US': 'IOI Labs, Inc. Bylaws | IOI Foundation',
      'es-ES': 'Estatutos de IOI Labs, Inc. | Fundación IOI',
      'fr-FR': 'Statuts de IOI Labs, Inc. | Fondation IOI',
      'de-DE': 'Satzung von IOI Labs, Inc. | IOI Stiftung',
    },
    description: {
      'en-US': 'The operative corporate bylaws for IOI Labs, Inc., published in PDF form with document context and direct download access.',
      'es-ES': 'Los estatutos corporativos vigentes de IOI Labs, Inc., publicados en PDF con contexto documental y acceso directo de descarga.',
      'fr-FR': 'Les statuts sociaux en vigueur de IOI Labs, Inc., publiés au format PDF avec contexte documentaire et accès direct au téléchargement.',
      'de-DE': 'Die gültigen Gesellschaftsstatuten von IOI Labs, Inc., als PDF veröffentlicht mit Dokumentkontext und direktem Downloadzugang.',
    },
    socialTitle: {
      'en-US': 'Corporate Bylaws',
      'es-ES': 'Estatutos corporativos',
      'fr-FR': 'Statuts sociaux',
      'de-DE': 'Gesellschaftsstatuten',
    },
    socialDescription: {
      'en-US': 'Current IOI Labs, Inc. corporate bylaws, published in full.',
      'es-ES': 'Los estatutos corporativos vigentes de IOI Labs, Inc., publicados íntegramente.',
      'fr-FR': 'Les statuts sociaux en vigueur de IOI Labs, Inc., publiés intégralement.',
      'de-DE': 'Die aktuellen Gesellschaftsstatuten von IOI Labs, Inc., vollständig veröffentlicht.',
    },
    noscriptHeading: {
      'en-US': 'Corporate Bylaws',
      'es-ES': 'Estatutos corporativos',
      'fr-FR': 'Statuts sociaux',
      'de-DE': 'Gesellschaftsstatuten',
    },
    noscriptBody: {
      'en-US': 'Access the current IOI Labs, Inc. bylaws PDF and the publication page describing the corporate document.',
      'es-ES': 'Accede al PDF actual de los estatutos de IOI Labs, Inc. y a la página de publicación que describe el documento corporativo.',
      'fr-FR': 'Accédez au PDF actuel des statuts de IOI Labs, Inc. et à la page de publication décrivant le document social.',
      'de-DE': 'Greifen Sie auf die aktuelle PDF-Fassung der Satzung von IOI Labs, Inc. und die Veröffentlichungsseite zum Gesellschaftsdokument zu.',
    },
  },
  governance: {
    path: '/governance',
    priority: '0.8',
    changefreq: 'monthly',
    ogType: 'article',
    schemaType: 'CollectionPage',
    name: {
      'en-US': 'Governance Framework',
      'es-ES': 'Marco de gobernanza',
      'fr-FR': 'Cadre de gouvernance',
      'de-DE': 'Governance-Rahmenwerk',
    },
    title: {
      'en-US': 'Governance Framework | IOI Foundation',
      'es-ES': 'Marco de gobernanza | Fundación IOI',
      'fr-FR': 'Cadre de gouvernance | Fondation IOI',
      'de-DE': 'Governance-Rahmenwerk | IOI Stiftung',
    },
    description: {
      'en-US': 'The governance framework describing steward review, constitutional limits, and the relationship between operations and the immutable charter.',
      'es-ES': 'El marco de gobernanza que describe la revisión de los custodios, los límites constitucionales y la relación entre operaciones y la carta inmutable.',
      'fr-FR': 'Le cadre de gouvernance décrivant l’examen des intendants, les limites constitutionnelles et le lien entre les opérations et la charte immuable.',
      'de-DE': 'Das Governance-Rahmenwerk, das Steward-Review, verfassungsrechtliche Grenzen und das Verhältnis zwischen Betrieb und unveränderlicher Charta beschreibt.',
    },
    socialTitle: {
      'en-US': 'Governance Framework',
      'es-ES': 'Marco de gobernanza',
      'fr-FR': 'Cadre de gouvernance',
      'de-DE': 'Governance-Rahmenwerk',
    },
    socialDescription: {
      'en-US': 'How protocol stewardship operates under constitutional constraints.',
      'es-ES': 'Cómo funciona la custodia del protocolo bajo restricciones constitucionales.',
      'fr-FR': 'Comment la stewardship du protocole fonctionne sous contrainte constitutionnelle.',
      'de-DE': 'Wie Protokoll-Stewardship unter verfassungsrechtlichen Beschränkungen arbeitet.',
    },
    noscriptHeading: {
      'en-US': 'Governance Framework',
      'es-ES': 'Marco de gobernanza',
      'fr-FR': 'Cadre de gouvernance',
      'de-DE': 'Governance-Rahmenwerk',
    },
    noscriptBody: {
      'en-US': 'Review the governance process, constitutional limits, and the public links connecting governance, bylaws, and the charter.',
      'es-ES': 'Revisa el proceso de gobernanza, los límites constitucionales y los enlaces públicos que conectan gobernanza, estatutos y carta.',
      'fr-FR': 'Consultez le processus de gouvernance, les limites constitutionnelles et les liens publics reliant gouvernance, statuts et charte.',
      'de-DE': 'Prüfen Sie den Governance-Prozess, die verfassungsrechtlichen Grenzen und die öffentlichen Verknüpfungen zwischen Governance, Satzung und Charta.',
    },
  },
  research: {
    path: '/research',
    priority: '0.8',
    changefreq: 'weekly',
    ogType: 'article',
    schemaType: 'CollectionPage',
    name: {
      'en-US': 'Technical Research Catalog',
      'es-ES': 'Catálogo de investigación técnica',
      'fr-FR': 'Catalogue de recherche technique',
      'de-DE': 'Katalog technischer Forschung',
    },
    title: {
      'en-US': 'Technical Research Catalog | IOI Foundation',
      'es-ES': 'Catálogo de investigación técnica | Fundación IOI',
      'fr-FR': 'Catalogue de recherche technique | Fondation IOI',
      'de-DE': 'Katalog technischer Forschung | IOI Stiftung',
    },
    description: {
      'en-US': 'A public catalog of long-horizon technical research, including post-quantum cryptography, formal verification, database systems, robotics runtime, and HHAI governance.',
      'es-ES': 'Un catálogo público de investigación técnica de largo plazo, incluyendo criptografía postcuántica, verificación formal, sistemas de bases de datos, runtime robótico y gobernanza HHAI.',
      'fr-FR': 'Un catalogue public de recherche technique de long terme, incluant la cryptographie post-quantique, la vérification formelle, les systèmes de bases de données, les runtimes robotiques et la gouvernance HHAI.',
      'de-DE': 'Ein öffentlicher Katalog langfristiger technischer Forschung, einschließlich Post-Quanten-Kryptographie, formaler Verifikation, Datenbanksystemen, Robotik-Runtimes und HHAI-Governance.',
    },
    socialTitle: {
      'en-US': 'Research Catalog',
      'es-ES': 'Catálogo de investigación',
      'fr-FR': 'Catalogue de recherche',
      'de-DE': 'Forschungskatalog',
    },
    socialDescription: {
      'en-US': 'Long-horizon technical work the Foundation is publishing and funding.',
      'es-ES': 'Trabajo técnico de largo plazo que la Fundación publica y financia.',
      'fr-FR': 'Travaux techniques de long terme que la Fondation publie et finance.',
      'de-DE': 'Langfristige technische Arbeit, die die Stiftung veröffentlicht und fördert.',
    },
    noscriptHeading: {
      'en-US': 'Technical Research Catalog',
      'es-ES': 'Catálogo de investigación técnica',
      'fr-FR': 'Catalogue de recherche technique',
      'de-DE': 'Katalog technischer Forschung',
    },
    noscriptBody: {
      'en-US': 'Browse the Foundation research catalog, including completed, in-progress, next, and future technical work.',
      'es-ES': 'Explora el catálogo de investigación de la Fundación, con trabajo técnico completado, en curso, siguiente y futuro.',
      'fr-FR': 'Parcourez le catalogue de recherche de la Fondation, incluant les travaux techniques terminés, en cours, à venir et futurs.',
      'de-DE': 'Durchsuchen Sie den Forschungskatalog der Stiftung mit abgeschlossener, laufender, nächster und zukünftiger technischer Arbeit.',
    },
  },
};
